## You should change each of the following fields
## to customize your blog

title: "My Data Science Blog"
description: "This is a place for me to blog about my projects and my awesome ideas." 
author: Emily Cook Bacon
author_description: "This description of who you are will appear on the 'About' page." 

url: https://emilycookbacon.github.io ## change this to https://yourusername.github.io
baseurl: /blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  emilycookbacon ## required
    twitter: 
    facebook: 
    email: e2cook98@byu.edu
    linkedin: emilycookbacon
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




